### ISSUE TITLE
Update password hashing to Argon2 

### ISSUE THREAD

**Issue by adamw** [softwaremill/bootzooka#915]
From scrypt, see: https://notes.volution.ro/v1/2022/07/notes/1290a79c/#password-hashes

**Comment by cipriancraciun** [comment]
Hi!  I'm the author of the pointed article, and I would just like to say that if you are already using `scrypt`, then switching to Argon2 isn't necessary, because `scrypt` isn't broken and doesn't have any vulnerabilities.  (In fact, `scrypt` has received quite some scrutiny over the years.)

Argon2 is just newer, and the "winner" of the password hashing competition (not a recommendation of NIST as I've wrongly mentioned in the article, something I'll have to correct sooner than later).

In fact, `scrypt` is already used in <https://github.com/FiloSottile/age> which wants to be modern alternative to GnuPG.

Thus, if you have time to spare, then perhaps you could invest that in auditing the other details related to the password management implementation, or provide additional features such as TOTP-based two-factor authentication, secure password generation, FIDO-based authentication, or integration with an identity provider like Google, GitHub, etc.  I would say any of these features would provide more real security than switching algorithms used to defend against brute force attacks.

Thanks for reading my article!  I hope it was useful.

**Comment by adamw** [comment]
@cipriancraciun thanks for the article and for getting back to us here - how did you find that corner of GitHub? :D

Anyway, good to know how the situation looks with scrypt/argon2. While doing research on this we've found out that the library we've been using for security so far has been archived, so we're looking for a better solution. Which might involve using scrypt or argon2, depending on what's available there.

Agreed on providing additional security mechanisms, however this repo is designed to be a minimalistic template for a (micro)service, so we're trying to keep the functionality at a minimum. But that also means keeping what *is* included up-to-date, so that when we do start a new project the template functionality doesn't need to be updated itself.

**Comment by cipriancraciun** [comment]
> @cipriancraciun thanks for the article and for getting back to us here - how did you find that corner of GitHub? :D

HTTP `Referer` headers.  :)  (Or in a couple of days via Google `link:example.com` searches.)

And I was amazed that these headers still work today (as in browsers still send them), in the age where everyone tries to "anonymize" everything...

(I'm not particularly pro or against these headers, however I believe for public documents, both source and target, they are extremely useful, so I'm glad they still work.)
